### ISSUE TITLE
How can i install Mac OS X Maverick or Yosemite on my S56CM

### ISSUE THREAD

**Issue by socheatsok78** [Brandon-T/S56CM-K56CM-MB#1]
I can't figured out how to install Mac OS X Yosemite on my Asus S56CM , Can you provide documentation, and how to use the tools you provided?

Thank before hand! :D

**Comment by socheatsok78** [comment]
I have a problem when selecting my USB drive - "Reboot and select proper boot device or insert boot media in selected"

**Comment by Brandon-T** [comment]
Your BIOS settings are incorrect. I can update some of the drivers above so that it includes USB3.0 but you still need to have the right BIOS settings for the installation. AFTER the installation, you can change them back so long as you have a USB3.0 driver.

**Comment by Acoisa** [comment]
how do you install clover to the usb?

**Comment by schristann** [comment]
Hello Brandon,

i managed installing OSX after having prepared the USB install media and installing Clover v 2.3k_r3241 on the USB driver. After the installation my asus reboots automatically. The next step in the readme is 6. where you advice to boot into usb in witch the following is displayed: 1: Boot OS X Install from OS X Yosemite 2:Boot Mac OS X from OS X 3: Boot Recovery
The next part of of step 6 says:
Mount the USB's EFI partition by using the following commands: mkdir /Volumes/EFI then use sudo mount -t msdos /dev/disk0s1 /Volumes/EFI to mount it.
Copy the EFI partition to your desktop and Eject the USB.
Install Clover onto the Yosemite HardDrive.

How am i supposed to to that. If I boot from the usb drive i get into the installation gui again. I can open a terminal an mount stuff, but i cannot install clover from here. Am i supposed to boot the new OS X from the stick? I tried that, but it failed with the funny symbol showing a crossed circle. Did i prepare the usb stick wrong with clover? Installing Clover on the usb stick was done by checking the option UEfi only in the customisation part. This was not mentioned in Part 3 of your tutorial. 
It only says: Install clover to the USB and an EFI partition will mount. Go to the EFI partition and copy the EFI folder from this github to it.
Installing Clover: Should i do that again without any options?

Maybe you can be of assistance? I Think i am not far away from a working installation.
